config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  namespace :api do
    namespace :v1 do
      resources :post, only: %i[index show]
    end
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :suggestions, only: %i[create new]
  end
  resources :suggestions, only: %i[index update destroy show] do
    resources :replies, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create show index destroy]
  resources :users, only: [:index]
  resources :approves
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { minimum: 10, maximum: 200 }, presence: true
  validates :user_id, presence: true
  validates :content, presence: true
  enum status: {
    pending: 0,
    approved: 1,
    not_approved: 2
  }
  validates :status, inclusion: { in: statuses.keys }

  belongs_to :user

  has_rich_text :content
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :suggestions, dependent: :destroy
  has_many :reports, as: :reportable, dependent: :destroy

  scope :recent_post, -> { order(updated_at: :desc).limit(5) }
  scope :order_posts, -> { order(updated_at: :desc) }
  scope :pending_posts, -> { where(status: 'pending') }
  scope :approved_posts, -> { where(status: 'approved') }
  delegate :name, to: :user, prefix: true
end

app/controllers/api/v1/post_controller.rb
class Api::V1::PostController < ApplicationController
  before_action :set_post, only: %i[show]
  skip_before_action :authenticate_user!, only: %i[index show]
  def index
    @posts = Post.includes(:user).approved_posts
    render json: @posts
    # render json: @posts.collect { |b| b.attributes_with_username_flag(b) }
  end

  def show
    @post = Post.find(params[:id])
    authorize @post, policy_class: PostPolicy
    render json: @post
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @posts = Post.includes(:user).approved_posts
  end

  def show
    @post = Post.find(params[:id])
    authorize @post, policy_class: PostPolicy
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = Post.new(post_params.merge(Published_date: Time.zone.now, user_id: current_user.id))
    if @post.save
      redirect_to post_url(@post), notice: 'Post was successfully created.'
    else
      flash[:notice] = @post.errors.full_messages.to_sentence
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @post.update(post_params)
      redirect_to post_url(@post), notice: 'Post was successfully updated.'
    else
      flash[:notice] = @post.errors.full_messages.to_sentence
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    flash[:notice] = if @post.destroy
                       'Post was successfully destroyed.'
                     else
                       @post.errors.full_messages.to_sentence
                     end
    redirect_to posts_url
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_user_check(post)
    user_signed_in? && (post.user.id == current_user.id)
  end
end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field text-start">
    <%= form.label :title ,class:"form-label" %>
    <%= form.text_field :title ,class:"form-control" ,required: true %>
  </div>
  <br>
  <div class="field posts-content">
    <%= form.label :content,class:"form-label" %>
    <%= form.rich_text_area :content ,class:"form-control",required: true %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Create Post" ,:class=>"btn btn-dark " %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<div class="Posts">
  <h1>Editing Post</h1>
  <%= render 'form', post: @post %>
  <div class="post-edit-buttons">
    <%= link_to 'Show', @post ,class:"btn btn-outline-dark" %> |
    <%= link_to 'Back', posts_path ,class:"btn btn-outline-dark" %>
  </div>
</div>

app/views/posts/index.html.erb
<div class="Posts-Index Posts">
  <h1>Posts</h1>
  <br>
  <div class="create-new-post">
    <%= link_to 'New Post', new_post_path ,class:"btn btn-dark" %>
  </div>
  <% @posts.order_posts.each do |post| %>
    <div class="row col-md-9 post-index-card">
      <div class="card mb-4 rounded-3 shadow post-index-card-body">
        <div class="card-header py-3 text-start">
          <h4 class="my-0 fw-normal"><%= post.user.name %> </h4>
          <h6 class="my-0 fw-normal text-muted"><%= post.updated_at.to_formatted_s(:short) %> </h6>
          <div class="text-end">
            <% if post_user_check(post) %>
              |
              <%= link_to 'Edit', edit_post_path(post) ,class:"btn btn-outline-dark" %>
              | <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } ,class:"btn btn-outline-dark" %>
            <% end %>
          </div>
        </div>
        <div class="card-body">
          <h3 class="card-title"><%= post.title %></h3>
          <%= link_to 'Continue Reading', post ,class:"w-100 btn  btn-outline-dark" %>
        </div>
      </div>
    </div>
    <hr>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="Posts">
  <h1>New Post</h1>
  <%= render 'form', post: @post %>
  <br>
  <hr>
  <%= link_to 'Back', posts_path ,class:"btn btn-dark" %>
</div>

app/views/posts/show.html.erb
<div class="Posts-Show Posts">
  <p id="notice"><%= notice %></p>
  <div class="row post-show-card">
    <div class="col-md-12">
      <div class="card mb-4 rounded-3 shadow">
        <div class="card-header py-3 text-start">
          <h4 class="my-0 fw-normal"><%= @post.user_name %> </h4>
          <h6 class="my-0 fw-normal text-muted"><%= @post.updated_at.to_formatted_s(:short) %> </h6>
          <h3 class="card-title"><%= @post.title %></h3>
          <div class="text-end">
            <%= link_to 'Suggest', new_post_suggestion_path(@post),class:"btn btn-primary" %>
          </div>
        </div>
        <div class="card-body">
          <p><%= @post.content %></p>
          <div class="like-button text-end" id="like-post">
            <%= render partial:'likes/button',locals:{likeable: @post} %>
          </div>
          <a href="#" class="post-report-display btn btn-danger">Report</a>
          <div class="post-form ">
            <%= render partial:'reports/form',locals:{reportable:  @post} %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="comment-section">
    <p>
      <%= render partial: 'comments/form',locals:{post: @post,parent: nil} %>
      <strong>Comments:</strong>
      <div id="comment-partials">
        <%= render @post.comments.sort_comments.order_by_id %>
      </div>
    </p>
  </div>
  <% if post_user_check(@post) %>
    <%= link_to 'Edit', edit_post_path(@post) ,class:"btn btn-outline-dark" %>
  <% end %>
</div>