config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  namespace :api do
    namespace :v1 do
      resources :post, only: %i[index show]
    end
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :suggestions, only: %i[create new]
  end
  resources :suggestions, only: %i[index update destroy show] do
    resources :replies, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create show index destroy]
  resources :users, only: [:index]
  resources :approves
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'
end

app/models/suggestion.rb
class Suggestion < ApplicationRecord
  validates :title, presence: true, length: { minimum: 10, maximum: 200 }
  validates :content, presence: true
  validates :user_id, presence: true
  validates :post_id, presence: true

  belongs_to :user
  belongs_to :post
  has_rich_text :content
  has_many :replies, dependent: :destroy

  delegate :name, to: :user, prefix: true
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  before_action :set_suggestion, only: %i[show update destroy]

  def index
    @user_posts = current_user.posts.all
  end

  def new
    @post = Post.find_by(id: params[:post_id])
    @suggestion = Suggestion.new(title: @post.title, content: @post.content)
  end

  def create
    @suggestion = current_user.suggestions.new(suggestion_params)
    flash[:alert] = @suggestion.errors.full_messages.to_sentence unless @suggestion.save!
    flash[:notice] = 'Your suggestion was successfully created.'
    redirect_to post_path(params[:post_id])
  end

  def update
    @post = @suggestion.post
    authorize @post, policy_class: SuggestionPolicy
    @post.title = @suggestion.title
    @post.content = @suggestion.content
    return unless @post.save!

    flash[:notice] = 'Your post was successfully updated with suggestion.'
    @suggestion.destroy!
    redirect_to suggestions_path
  end

  def show
    authorize @suggestion, policy_class: SuggestionPolicy
  end

  def destroy
    authorize @suggestion, policy_class: SuggestionPolicy
    redirect_to suggestions_url, notice: 'Suggestion was successfully destroyed.' if @suggestion.destroy
  end

  private

  def set_suggestion
    @suggestion = Suggestion.find_by(id: params[:id])
  end

  def suggestion_params
    params.require(:suggestion).permit(:title, :content).merge(post_id: params[:post_id])
  end
end

app/views/suggestions/_form.html.erb
<%= form_with(model: suggestion ,url: post_suggestions_path, local: true) do |form| %>
  <div class="suggestion-title">
    <h3><strong><%= form.label :title,class:"form-label" %> </strong></h3>
    <%= form.text_field :title,class:"form-control" ,required: true %>
  </div>
  <div class="suggestion-content">
    <h3><strong><%= form.label :content ,class:"form-label" %></strong></h3>
    <%= form.rich_text_area :content ,class:"form-control",required: true %>
  </div>
  <br>
  <div class="actions">
    <%= form.submit "Create Suggestion" ,:class=>"btn btn-dark " %>
  </div>
<% end %>

app/views/suggestions/index.html.erb
<div class="">
  <h1>Suggestions Made For your Post</h1>
</div>
<% @user_posts.each do |post| %>
  <% post.suggestions.all.each do |suggestion| %>
    <div class="row col-md-9 post-index-card">
      <div class="card mb-4 rounded-3 shadow post-index-card-body">
        <div class="card-header py-3 text-start">
          <h4 class="my-0 fw-normal"><%= suggestion.user_name %> </h4>
          <h6 class="my-0 fw-normal text-muted"><%= suggestion.created_at.to_formatted_s(:short) %> </h6>
        </div>
        <div class="card-body">
          <h3 class="card-title"><%= suggestion.title %></h3>
          <%= link_to 'Show', suggestion ,class:" w-100 btn btn-outline-dark" %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<br>
<div class="user-suggestions conatiner">
  <h1>Suggestions You Made</h1>
  <% current_user.suggestions.each do |suggestion| %>
    <div class="card shadow col-md-9 rounded-3">
      <div class="card-header py-3 text-start">
        <h4 class="my-0 fw-normal"><%= suggestion.user_name %> </h4>
        <h6 class="my-0 fw-normal text-muted"><%= suggestion.created_at.to_formatted_s(:short) %> </h6>
      </div>
      <div class="card-body">
        <h3 class="card-title"><%= suggestion.title %></h3>
        <%= link_to 'Show', suggestion ,class:" w-100 btn btn-outline-dark" %>
      </div>
    </div>
    <hr>
  <% end %>
</div>
<%= link_to "Back",posts_path,class:"btn btn-primary me-2" %>

app/views/suggestions/new.html.erb
<%= render partial: 'suggestions/form',locals:{suggestion: @suggestion,post: @post} %>

app/views/suggestions/show.html.erb
<div class="Suggestion-Show Suggestions">
  <div class="row card reports-card">
    <div class="card-body shadow ">
      <p id="notice"><%= notice %></p>
      <div class="field Post-Header-Show">
        <h3><%= @suggestion.user.name %> </h3>
        <span class="text-muted"><%= @suggestion.updated_at.to_formatted_s(:short) %></span>
      </div>
      <p class="field">
        <h4>Title</h4>
        <%= @suggestion.title %>
      </p>
      <div class="suggestion-content img-fluid">
        <p><%= @suggestion.content %></p>
      </div>
      <% if current_user==@suggestion.post.user %>
        <%= link_to "Update Post",suggestion_path(@suggestion),method: :put ,class:"btn btn-success me-2" %>
        <%= link_to "Reject",@suggestion,method: :delete ,class:"btn btn-danger me-2",data: { confirm: 'Are you sure?' } %>
      <% end %>
      <%= link_to "Back",suggestions_path,class:"btn btn-primary me-2" %>
    </div>
  </div>
  <p>
    <strong>Replies:</strong>
    <%= render @suggestion.replies.includes(:user) %>
    <%= render partial: 'replies/form',locals: {suggestion: @suggestion} %>
  </p>
</div>