config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get 'errors/not_found'
  get 'errors/internal_server_error'
  match '/404', to: 'errors#not_found', via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  namespace :api do
    namespace :v1 do
      resources :post, only: %i[index show]
    end
  end

  resources :posts do
    resources :comments, only: [:create]
    resources :suggestions, only: %i[create new]
  end
  resources :suggestions, only: %i[index update destroy show] do
    resources :replies, only: [:create]
  end
  resources :comments, only: [:destroy]
  resources :likes, only: %i[create destroy]
  resources :reports, only: %i[create show index destroy]
  resources :users, only: [:index]
  resources :approves
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'
end

app/models/report.rb
class Report < ApplicationRecord
  validates :reason, presence: true, length: { minimum: 10, maximum: 500 }
  validates :user_id, presence: true
  validates :reportable_type, presence: true
  validates :reportable_id, presence: true

  belongs_to :user
  belongs_to :reportable, polymorphic: true

  delegate :name, to: :user, prefix: true
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: %i[show destroy]
  before_action :pundit_authorization, only: %i[show index destroy]
  def create
    @report = current_user.reports.new(report_params)
    authorize @report
    if @report.save
      redirect_back(fallback_location: posts_path)
    else
      flash[:notice] = @report.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def show; end

  def index
    @report = Report.includes(:user)
  end

  def destroy
    if @report.destroy
      redirect_to reports_url, notice: 'report was successfully destroyed.'
    else
      flash[:notice] = @report.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def pundit_authorization
    authorize @report, policy_class: ReportPolicy
  end

  def set_report
    @report = Report.find_by(id: params[:id])
  end

  def report_params
    params.require(:report).permit(:reason, :reportable_id, :reportable_type)
  end
end

app/views/reports/_form.html.erb
<form action="/reports" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="report[reportable_id]" value="<%= reportable.id %>">
  <input type="hidden" name="report[reportable_type]" value="<%= reportable.class.to_s %>">
  <div class="field col-2">
    <textarea name="report[reason]" cols="10" rows="3" class="form-control" required="required"></textarea>
  </div>
  <input type="submit" value="Report" class="btn btn-outline-secondary">
</form>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>
<div class="Reports-index">
  <h1>Reports</h1>
  <% @report.each do |report| %>
    <div class="row card reports-card">
      <div class="card-body shadow ">
        <p><strong>Report Made By:</strong></p>
        <p><strong><%= report.user_name %></strong></p>
        <p><strong>Reason:</strong></p>
        <%= report.reason %>
        <div class="report">
          <%= link_to 'Details', report ,class:"report-detail-btn btn btn-outline-dark" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reports/show.html.erb
<div class="Reports-Show Reports">
  <p id="notice"><%= notice %></p>
  <div class="row card reports-card">
    <div class="card-body shadow ">
      <div class="field Post-Header-Show">
        <h3><%= @report.user.name %> </h3>
        <span class="text-muted"><%= @report.updated_at.to_formatted_s(:short) %></span>
      </div>
      <p class="field">
        <h4>Reason</h4>
        <%= @report.reason %>
      </p>
      <% if @report.reportable.class==Comment %>
        <div class="report-content">
          <strong><small>Comment:</small></strong>
          <p><%= @report.reportable.body %></p>
          <% if @report.reportable.image.attachment!=nil %>
            <p><%= cl_image_tag(@report.reportable.image.key) %></p>
          <% end %>
          <Strong><small>This Comment Was Made by:</small></Strong>
          <p><%= @report.reportable.user.name %></p>
        </div>
        <%= link_to "Reject",@report,method: :delete ,class:"btn btn-danger me-2",data: { confirm: 'Are you sure?' } %>
        <%= link_to "Delete Comment",comment_path(@report.reportable),method: :delete ,class:"btn btn-danger me-2",data: { confirm: 'Are you sure?' } %>
      <% else %>
        <strong><small>Post:</small></strong>
        <p class="field">
          <h4>Title</h4>
          <%= @report.reportable.title %>
        </p>
        <div class="report-post-content img-fluid">
          <p><%= @report.reportable.content %></p>
        </div>
        <Strong><small>This Post Was Made by:</small></Strong>
        <p><%= @report.reportable.user.name %></p>
        <%= link_to "Reject",@report,method: :delete ,class:"btn btn-danger me-2",data: { confirm: 'Are you sure?' } %>
        <%= link_to "Delete Post",post_path(@report.reportable),method: :delete ,class:"btn btn-danger me-2",data: { confirm: 'Are you sure?' } %>
      <% end %>
    </div>
  </div>
  <hr>
  <%= link_to "Back",reports_path,class:"btn btn-primary me-2" %>